#pragma once

//hook names

#define PTOS_HOOKNAME_CREATE_APPLICATION		createApplication
#define PTOS_HOOKNAME_START_APPLICATION			startApplication
#define PTOS_HOOKNAME_END_APPLICATION			endApplication
#define PTOS_HOOKNAME_PRE_UPDATE				preUpdate
#define PTOS_HOOKNAME_POST_UPDATE				postUpdate

//hook signatures

#define _PTOS_HOOKDEF_CREATE_APPLICATION(ns)	ns Application* ns PTOS_HOOKNAME_CREATE_APPLICATION()
#define _PTOS_HOOKDEF_START_APPLICATION(ns)		void ns PTOS_HOOKNAME_START_APPLICATION(ns ApplicationContextManager& ctx)
#define _PTOS_HOOKDEF_END_APPLICATION(ns)		void ns PTOS_HOOKNAME_END_APPLICATION(ns Application* application)
#define _PTOS_HOOKDEF_PRE_UPDATE(ns)			void ns PTOS_HOOKNAME_PRE_UPDATE(ns ApplicationContextManager& ctx)
#define _PTOS_HOOKDEF_POST_UPDATE(ns)			void ns PTOS_HOOKNAME_POST_UPDATE(ns ApplicationContextManager& ctx)

#define PTOS_HOOK_CREATE_APPLICATION			_PTOS_HOOKDEF_CREATE_APPLICATION(PTOS::)
#define PTOS_HOOK_START_APPLICATION				_PTOS_HOOKDEF_START_APPLICATION(PTOS::)
#define PTOS_HOOK_END_APPLICATION				_PTOS_HOOKDEF_END_APPLICATION(PTOS::)
#define PTOS_HOOK_PRE_UPDATE					_PTOS_HOOKDEF_PRE_UPDATE(PTOS::)
#define PTOS_HOOK_POST_UPDATE					_PTOS_HOOKDEF_POST_UPDATE(PTOS::)

//hook defaults

#define PTOS_HOOK_CREATE_APPLICATION_DEFAULT	PTOS_HOOK_CREATE_APPLICATION { return new PTOS::Application(); }
#define PTOS_HOOK_START_APPLICATION_DEFAULT		PTOS_HOOK_START_APPLICATION {}
#define PTOS_HOOK_END_APPLICATION_DEFAULT		PTOS_HOOK_END_APPLICATION { delete application; }
#define PTOS_HOOK_PRE_UPDATE_DEFAULT			PTOS_HOOK_PRE_UPDATE {}
#define PTOS_HOOK_POST_UPDATE_DEFAULT			PTOS_HOOK_POST_UPDATE {}

//Use all hook defaults
#define PTOS_HOOKS_DEFAULTS \
PTOS_HOOK_CREATE_APPLICATION_DEFAULT \
PTOS_HOOK_START_APPLICATION_DEFAULT \
PTOS_HOOK_END_APPLICATION_DEFAULT \
PTOS_HOOK_PRE_UPDATE_DEFAULT \
PTOS_HOOK_POST_UPDATE_DEFAULT
